---
- name: install tools
  apt: name={{item}} state=present
  with_items:
    - python-httplib2

- name: install nginx
  apt: name=nginx state=present 

- name: configure nginx state
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/{{ item.key }} mode=0665
  with_dict: 
    - "{{ sites }}"
  notify: restart nginx

- name: get active sites
  shell: ls -1 /etc/nginx/sites-enabled
  register: active
  changed_when: "active.stdout_lines !=  sites.keys()" 
  tags: [ 'configure' ]

- debug: var=active.stdout_lines 

- name: de-activate default nginx site
  file: path=/etc/nginx/sites-enabled/{{ item }} state=absent
  with_items: active.stdout_lines
  when: item not in sites
  notify: restart nginx

- name: activate demo nginx site
  file: src=/etc/nginx/sites-available/{{ item.key }} dest=/etc/nginx/sites-enabled/{{ item.key }} state=link
  with_dict: 
    - "{{ sites }}"
  notify: restart nginx

- name: ensure nginx started
  service: name=nginx state=started enabled=yes

