---
  - hosts: control
    become: true
    tags: [ 'packages' ]
    tasks:
      - name: install tools
        apt: name={{item}} state=present 
        with_items:
          - curl
          - python-httplib2
     
