---
- hosts: loadbalancer 
  become: true
  gather_facts: false 
  tasks: 
    - name: verify nginx 
      command: service nginx status
      changed_when: false   

    - name: verify nginx lis on 80
      wait_for: port=80 timeout=1

- hosts: webserver
  become: true
  tasks:
    - name: verify apache2
      command: systemctl status apache2
      changed_when: false

    - name: verify nginx lis on 80
      wait_for: port=80 timeout=1 

- hosts: database
  become: true
  tasks:
    - name: verify mysql
      command: service mysql status

    - name: verify nginx lis on 3306
      wait_for: port=3306 timeout=1

- hosts: control 
  gather_facts: false 
  tasks:
    - name: verify end-to-end response
      uri: url=http://{{item}} return_content=yes
      with_items: "{{ groups.loadbalancer }}"
      register: lb_index

    - fail: msg="index failed to return content"
      when: "'Hello, from sunny' not in item.content"
      with_items: "{{lb_index.results}}"
    
- hosts: loadbalancer
  gather_facts: false
  tasks:
    - name: verify backend response
      uri: url=http://{{item}} return_content=yes
      with_items: "{{  groups.webserver }}"
      register: app_index

    - fail: msg="index failed to return content"
      when: "'Hello, from sunny' not in item.content"
      with_items: "{{app_index.results}}"

